#!/usr/bin/with-contenv bash

while IFS='=' read -r name value; do
  case "$name" in
    FILE__*)
      target_name="${name#FILE__}"
      if [ -n "$value" ] && [ -r "$value" ]; then
        export "${target_name}=$(cat "$value")"
        echo "Loaded secret for ${target_name}"
      fi
      ;;
  esac
done < <(env)
